In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
housing_data = pd.read_csv('HousingData.csv', encoding = 'unicode_escape')
housing_data.head()

,nav-link href,listing-location,price,bed,bath,listing-floorarea,listing-floorarea 2
0,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.0,5.0,420 m²,Rp 20.720.721 per m²
1,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.0,3.0,190 m²,Rp 12.747.875 per m²
2,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.0,3.0,132 m²,Rp 30.859.375 per m²
3,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.0,3.0,220 m²,Rp 18.333.333 per m²
4,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.0,2.0,180 m²,Rp 27.777.778 per m²

Preprocessing

In [4]:
housing_data = housing_data.rename(columns = {'nav-link href':'url', 'listing-location': 'location',
                               'listing-floorarea':'area'})

housing_data = housing_data.drop(columns = 'listing-floorarea 2')
housing_data = housing_data.drop_duplicates()
housing_data.head()

,url,location,price,bed,bath,area
0,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.0,5.0,420 m²
1,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.0,3.0,190 m²
2,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.0,3.0,132 m²
3,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.0,3.0,220 m²
4,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.0,2.0,180 m²

Splitting into Train and Test sets

In [22]:
y = housing_data['price'] 
X = housing_data.drop(columns = 'price')

X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 1, test_size = 0.2)

#combining these split datasets
train_data = X_train
train_data['price'] = y_train

test_data = X_test
test_data['price'] = y_test

In [34]:
train_data.head()

,url,location,bed,bath,area,price
20360,https://www.rumah.com/listing-properti/dijual-...,"Jalan camar bintaro sektor 3, Bintaro, Tangera...",3.0,2.0,200 m²,"4,8 M"
21203,https://www.rumah.com/listing-properti/dijual-...,"Ciputat Timur, Tangerang Selatan, Banten",4.0,4.0,200 m²,"2,7 M"
26019,https://www.rumah.com/listing-properti/dijual-...,"Ciputat, Tangerang Selatan, Banten",4.0,3.0,110 m²,"1,375 M"
6750,https://www.rumah.com/listing-properti/dijual-...,"Pondok Ranji, Bintaro, Tangerang Selatan, Banten",5.0,5.0,232 m²,"4,25 M"
16352,https://www.rumah.com/listing-properti/dijual-...,"1 jl.Jombang ,Bintaro, Pondok Aren, Tangerang...",7.0,5.0,540 m²,"5,5 M"

In [32]:
test_data.head()

,url,location,bed,bath,area,price
461,https://www.rumah.com/listing-properti/dijual-...,"Ciputat Timur, Tangerang Selatan, Banten",6.0,4.0,200 m²,"3,75 M"
3358,https://www.rumah.com/listing-properti/dijual-...,"Graha Raya, Bintaro, Tangerang Selatan, Banten",3.0,3.0,100 m²,"1,3 M"
20663,https://www.rumah.com/listing-properti/dijual-...,"Bintaro, Tangerang Selatan, Banten",5.0,5.0,144 m²,"4,1 M"
516,https://www.rumah.com/listing-properti/dijual-...,"Kucica bintaro sektor 9, Bintaro, Tangerang Se...",4.0,3.0,300 m²,"4,9 M"
27079,https://www.rumah.com/listing-properti/dijual-...,"Bintaro, Tangerang Selatan, Banten",5.0,6.0,350 m²,"3,75 M"

Converting to csv

In [29]:
train_data.to_csv('train.csv')  
test_data.to_csv('test.csv')